# Generated by Django 5.1.4 on 2024-12-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the audio file', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the audio file')),
                ('file', models.FileField(help_text='Upload the audio file', upload_to='audio_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of upload')),
            ],
        ),
    ]
