# Generated by Django 5.1.4 on 2024-12-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the audio icon', null=True, upload_to='audio_icons/'),
        ),
    ]
