# Generated by Django 5.1.4 on 2024-12-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_audiofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the music link', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the music link')),
                ('url', models.URLField(help_text='URL of the music link', max_length=300)),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image for the music link', null=True, upload_to='link_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation')),
            ],
        ),
    ]
